version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-get-instance-list:
    executor: aws-cli/default
    steps:
      - checkout
      - run: echo [all] > inventory.txt
      - run:
          name: Get instances
          command: >
            echo $(aws ec2 describe-instances 
            --query 'Reservations[*].Instances[*].PublicIpAddress' 
            --output text) >> inventory.txt
      - run: ls -al
      - run: cat inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - inventory.txt
  restore-inventory:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ls -al
      - run: cat inventory.txt
  create-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation stack
          command: >
            aws cloudformation deploy
            --template-file ubuntu_server.yml
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
            --region us-west-2
      - run:
          name: Update inventory file
          command: |
            echo [all] > inventory.txt
            echo $(aws ec2 describe-instances \
            --query 'Reservations[*].Instances[*].PublicIpAddress' \
            --output text) >> inventory.txt
      - run: cat inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - inventory.txt
  configure-infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['63:e6:ee:ef:ea:88:47:06:47:b7:b6:0e:29:b9:2b:61']
      - run:
          name: Install deps
          command: |
            apk add --update ansible
      - attach_workspace:
          at: .
      - run: ls -al
      - run: cat inventory.txt
      - run:
          name: configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  aws-cli:
    jobs:
      # - aws-get-instance-list
      # - restore-inventory:
      #     requires:
      #       - aws-get-instance-list
      - create-infra
      - configure-infra
