version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: udaciuser
      - run:
          name: Get instances
          command: >
            aws ec2 describe-instances 
            --query 'Reservations[*].Instances[*].PublicIpAddress' 
            --output text >> inventory.txt
      - run: ls -al
      - run: pwd
      - save_cache:
          key: inventory
          paths:
            - ./inventory.txt
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
