version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-config-and-get-instance-list:
    environment:
      - PARAM_AWS_CLI_REGION: us-west-2
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run: aws configure set aws_access_key_id $PARAM_AWS_CLI_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $PARAM_AWS_CLI_SECRET_ACCESS_KEY
      - run: aws configure set default.region $PARAM_AWS_CLI_REGION
      - run: echo [all] > inventory.txt
      - run:
          name: Get instances
          command: >
            echo $(aws ec2 describe-instances 
            --query 'Reservations[*].Instances[*].PublicIpAddress' 
            --output text) >> inventory.txt
      - run: ls -al
      - run: cat inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - inventory.txt
      # - save_cache:
      #     key: inventory
      #     paths:
      #       - ./inventory.txt
  restore-inventory:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      # - restore_cache:
      #     keys:
      #       - inventory
      - run: ls -al
      - run: cat inventory.txt
  test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo hello world
  create-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation stack
          command: >
            aws cloudformation deploy
            --template-file ubuntu_server.yml
            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
            --region us-west-2
workflows:
  aws-cli:
    jobs:
      - test
      - aws-config-and-get-instance-list
      - restore-inventory:
          requires:
            - aws-config-and-get-instance-list
      - create-infra
