version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    environment:
      - PARAM_AWS_CLI_REGION: us-west-2
    executor: aws-cli/default
    steps:
      - checkout
      # - aws-cli/setup:
      #     profile-name: udaciuser
      - run: aws configure set aws_access_key_id $PARAM_AWS_CLI_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $PARAM_AWS_CLI_SECRET_ACCESS_KEY
      - run: aws configure set default.region $PARAM_AWS_CLI_REGION
      - run: aws configure list
      - run: aws iam list-users
      - run: echo [all] > inventory.txt
      - run:
          name: Get instances
          command: |
            aws ec2 describe-instances 
            --query 'Reservations[*].Instances[*].PublicIpAddress' 
            --output text >> inventory.txt
      - run: ls -al
      - run: cat inventory.txt
      - save_cache:
          key: inventory
          paths:
            - ./inventory.txt
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
