version: '2.1'

jobs:
  create-and-deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute new_bucket.yml - Create CF stack
          command: |
            aws cloudformation deploy \
            --template-file infra/new_bucket.yml \
            --stack-name new-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
            --parameter-overrides S3BucketName="new-bucket-${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync . s3://new-bucket-${CIRCLE_WORKFLOW_ID:0:7} --delete
      - run:
          name: destroy-frontend
          when: on_fail
          command: aws cloudformation delete-stack --stack-name new-bucket-${CIRCLE_WORKFLOW_ID:0:7}
  get-last-deployment-id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: Fetch and save old pipelineID (bucketname) responsible for the last release
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`S3BucketName\`].Value" \
            --no-paginate --output text > ~/textfile.txt
      - run: |
          aws cloudformation \
          list-exports --query "Exports[?Name==\`S3BucketName\`].Value" \
          --no-paginate --output text
      - persist_to_workspace:
          root: ~/
          paths:
            - textfile.txt
      - run: cat ~/textfile.txt
  promote-to-prod:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml
          command: |
            aws cloudformation deploy \
            --template-file infra/cloudfront.yml \
            --stack-name cloudfront \
            --parameter-overrides S3BucketName=new-bucket-${CIRCLE_WORKFLOW_ID:0:7}
  clean-up-old-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - attach_workspace:
          at: ~/
      - run: ls ~
      - run: cat ~/textfile.txt
      - run:
          name: Destroy old bucket and cloudformation stack
          command: |
            export OldBucket=$(cat ~/textfile.txt)
            aws s3 rm "s3://${OldBucket}" --recursive
            aws cloudformation delete-stack --stack-name old-bucket

workflows:
  blue-to-green:
    jobs:
      - create-and-deploy-frontend
      - promote-to-prod:
          requires:
            - create-and-deploy-frontend
      - get-last-deployment-id
      - clean-up-old-frontend:
          requires:
            - get-last-deployment-id
            - promote-to-prod
