version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  aws-cli-example:
    environment:
      - PARAM_AWS_CLI_REGION: us-west-2
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: udaciuser
      - run: echo $PARAM_AWS_CLI_ACCESS_KEY_ID
      - run: echo $PARAM_AWS_CLI_SECRET_ACCESS_KEY
      - run: echo $PARAM_AWS_CLI_REGION
      - run: aws configure list
      - run:
          name: Get instances
          command: aws ec2 describe-instances -query 'Reservations[*].Instances[*].PublicIpAddress' --output text
      - run: ls -al
      - run: pwd
      - save_cache:
          key: inventory
          paths:
            - ./inventory.txt
workflows:
  aws-cli:
    jobs:
      - aws-cli-example
