version: 2.1
docker-default: &docker-node
  docker:
    - image: circleci/node:14
jobs:
  get-inventory:
    docker:
      - image: circleci/awscli
    steps:
      - add_ssh_keys:
          fingerprints:
            - a0:a8:5a:af:03:a2:b2:bd:b6:38:10:87:06:75:e3:b2
      - run: echo [all] > inventory.txt
      - run:
          name: Get instances
          command: >
            aws ec2 describe-instances 
            --query 'Reservations[*].Instances[*].PublicIpAddress' 
            --output text >> inventory.txt
      - run: ls -al
      - run: pwd
      - save_cache:
          key: inventory
          paths:
            - ./inventory.txt
  restore_inventory:
    <<: *docker-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - inventory
      - run: ls -al
      - run: pwd

workflows:
  main:
    jobs:
      - get-inventory
      - restore_inventory:
          requires:
            - get-inventory
